name = "filcdn-worker"
main = "bin/worker.js"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

[env.dev.vars]
ENVIRONMENT = "dev"
CACHE_TTL = 86400

[env.production.vars]
ENVIRONMENT = "production"
CACHE_TTL = "$CACHE_TTL"
