name = "filcdn-worker"
main = "bin/worker.js"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

[env.dev.vars]
ENVIRONMENT = "dev"
CACHE_TTL = 86400
DNS_ROOT = ".localhost"

[env.production.vars]
ENVIRONMENT = "production"
CACHE_TTL = 86400
DNS_ROOT = ".calibration.filcdn.io"

[[d1_databases]]
binding = "DB"
database_name = "filcdn-db"
database_id = "8cc92155-16f6-426a-b782-2965e0daf103"
